default_language_version:
    python: python3.12
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python3 -m black --config pyproject.toml
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: python3 -m isort
        language: system
        types: [python]